# Generated by Django 5.0.3 on 2024-04-28 05:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Creator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 28, 5, 47, 48, 464751, tzinfo=datetime.timezone.utc)),
        ),
    ]
