# Generated by Django 5.0.3 on 2024-04-28 05:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Creator', '0002_alter_client_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='username',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 28, 5, 57, 57, 429774, tzinfo=datetime.timezone.utc)),
        ),
    ]
