# Generated by Django 5.0.3 on 2024-04-29 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Creator', '0003_client_username_alter_client_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 29, 13, 43, 6, 946256, tzinfo=datetime.timezone.utc)),
        ),
    ]
