# Generated by Django 5.0.3 on 2024-05-08 19:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Creator', '0005_client_encryption_key_alter_client_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='in_user',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 8, 19, 21, 27, 431095, tzinfo=datetime.timezone.utc)),
        ),
    ]
